[project]
name = "ytldl2"
authors = [{ name = "Niakr1s", email = "pavel2188@gmail.com" }]
description = "YouTube music local library"
readme = "README.md"
version = "0.1.0"
requires-python = ">=3.11"
keywords = ["youtube", "music", "youtube music"]
license = { file = "LICENSE" }
classifiers = ["Programming Language :: Python :: 3"]
dependencies = []

[project.urls]
Github = "https://github.com/niakr1s/ytldl2"

[project.optional-dependencies]
dev = ["pytest"]

[project.scripts]
ytldl2 = "ytldl2_cli.cli:main"
